
---
- hosts: all
  become: yes
  tasks:

  - name: apt-get update -y
    shell: apt-get update -y
      
  - name: apt-get update -y
    shell: apt-get update -y
    
  - name: apt-get dist-upgrade -y
    shell: apt-get dist-upgrade -y
