---
- hosts: all
  become: yes
  tasks: 
    - name: Turn off memcached
      command: systemctl stop memcached

    - name: Configuring memcached size
      lineinfile:
        dest: /etc/memcached.conf 
        regexp: '^(.*)-m(.*)$' 
        line: "-m {{ memcached_size }}"
        backrefs: yes

    - name: Turn on memcached
      command: systemctl start memcached
