---
- hosts: all
  become: yes
  tasks: 
  - name: Install packages
    apt:
      name:
      - aptitude
      - mariadb-server
      - apache2
      - php7.2
      - imagemagick
      - wget
      - rsync
      - git
      - ncdu
      - unzip
      - mlocate
      - p7zip
      - p7zip-full
      - unzip
      - zip
      - libapache2-mod-php7.2
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-cgi
      - php7.2-cli
      - php7.2-common
      - php7.2-curl
      - php7.2-imap
      - php7.2-intl 
      - php7.2-pspell
      - php7.2-sqlite3
      - php7.2-tidy
      - php7.2-opcache
      - php7.2-json
      - php7.2-bz2
      - php7.2-readline
      - php7.2-xmlrpc 
      - php7.2-enchant
      - php7.2-xsl
      - php7.2-zip
      - php7.2-bcmath
      - php7.2-imagick
      - php7.2-readline
      - php-memcached
      - php-memcache
      - memcached
      - libmemcached-tools
      state: latest
      cache_valid_time: 3600    # update cache if more than an hour old
