---
- hosts: all
  become: yes
  tasks:  
  - name: Install packages
    apt:
      name:
      - aptitude
      - mariadb-server
      - apache2
      - php7.2
      - imagemagick
      - wget
      - rsync
      - git
      - ncdu
      - unzip
      - mlocate
      - p7zip
      - p7zip-full
      - unzip
      - zip
      - libapache2-mod-php7.2
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-cgi
      - php7.2-cli
      - php7.2-common
      - php7.2-curl
      - php7.2-imap
      - php7.2-intl 
      - php7.2-pspell
      - php7.2-sqlite3
      - php7.2-tidy
      - php7.2-opcache
      - php7.2-json
      - php7.2-bz2
      - php7.2-readline
      - php7.2-xmlrpc 
      - php7.2-enchant
      - php7.2-xsl
      - php7.2-zip
      - php7.2-bcmath
      - php7.2-imagick
      - php7.2-readline
      - php7.2-mysql
      - php7.2-mysqli
      - php7.2-gd
      - php-memcached
      - php-memcache
      - memcached
      - libmemcached-tools
      - ssl-cert
      - python-pymysql
      - nodejs
      - cmdtest
      - certbot
      state: latest
      
  - name: Apache SSL 1
    command: a2enmod ssl 
    
  - name: Apache SSL 2
    command: sudo a2ensite default-ssl
    
  - name: Apache SSL 3
    command: sudo a2enmod deflate
    
  - name: Apache SSL 4
    command: sudo a2enmod rewrite
    
  - name: Install Composer 1
    command: wget https://getcomposer.org/composer.phar
    
  - name: Install Composer 2
    command: chmod +x composer.phar
    
  - name: Install Composer 3
    command: sudo mv composer.phar /usr/local/bin/composer
    
  - name: Install Composer 4
    command: sudo ln -sf /usr/local/bin/composer /usr/bin/composer
      
  - name: Drush install 0
    command: sudo rm -rf /usr/local/src/drush

  - name: Drush install 1
    command: sudo git clone https://github.com/drush-ops/drush.git /usr/local/src/drush

  - name: Drush install 2
    shell: "cd /usr/local/src/drush && sudo git checkout 8.3.0 && sudo ln -sf /usr/local/src/drush/drush /usr/bin/drush && sudo composer install"

  - name: Ansible copy file force 1
    copy:
      src: ../files/opcache.ini
      dest: /etc/php/7.2/apache2/conf.d/10-opcache.ini
      force: yes
      
  - name: Ansible copy file force 2
    copy:
      src: ../files/php.ini
      dest: /etc/php/7.2/apache2/php.ini
      force: yes
      
  - name: Ansible copy file force 3
    copy:
      src: ../files/apache2.conf
      dest: /etc/apache2/apache2.conf
      force: yes

  - name: Turn off memcached
    command: systemctl stop memcached

  - name: Configuring memcached size
    lineinfile:
      dest: /etc/memcached.conf 
      regexp: '^(.*)-m 64(.*)$' 
      line: "-m {{ memcached_size }}"
      backrefs: yes

  - name: Turn on memcached
    command: systemctl start memcached
     
  - name: fix_permissions.
    shell: chown -R www-data:www-data /var/www/html/

  - name: Turn off vhost 1
    command: a2dissite 000-default.conf 

  - name: add to default-ssl.conf
    blockinfile:
      dest: /etc/apache2/sites-available/default-ssl.conf
      insertafter: EOF
      state: present
      content: |
        <VirtualHost *:443>
        DocumentRoot "/var/www/html/VAR_FOLDER_NAME"
        ServerName VAR_DOMAIN_1
        ServerAlias VAR_DOMAIN_2
        </VirtualHost>
     
  - name: restart apache2
    shell: systemctl restart apache2
      
