---
- hosts: all
  become: yes
  tasks: 
    
    - name: upgrade all packages, with exclude support
      yum:
        name: '*'
        state: latest
        exclude: "{{ upgrade_exclude_packages }}"
        
  - debug: msg="{{ details.stdout_lines | quote }}"
