---
- hosts: all
  become: yes
  tasks: 
    
    - name: upgrade all packages, with exclude support
      yum:
        name: '*'
        state: latest
        exclude: "{{ upgrade_exclude_packages }}"
        
    - name: cat file
      shell: cat /etc/os-release 
      register: cat_content_file

    - name: echo file
      debug:
        msg: "{{ cat_content_file.stdout }}"
