---
- hosts: all
  become: yes
  tasks: 
 
    - name: Ansible copy file force
      copy:
        src: ../files/.bash_aliases
        dest: ~/.bash_aliases 
        force: yes

    - name: update system 1
      command: apt-get update
      
    - name: update system 2
      command: apt-get upgrade -y
      
    - name: update system 3
      command: apt-get dist-upgrade -y
      
    - name: update system 4
      command: add-apt-repository universe
      
    - name: update system 5
      command: add-apt-repository multiverse
   
    - name: Install packages
      apt:
        name:
        - ccrypt
        - lsof
        - net-tools
        - htop
        - nano
        - wget
        - rsync
        - git
        - ncdu
        - nload
        - mc
        - iotop
        - mdadm
        - unzip
        - iperf3
        - mlocate
        - tree
        - p7zip
        - p7zip-full
        - p7zip-rar 
        - aptitude
        state: latest









    - name: Ansible copy file force
      copy:
        src: ../files/sshd_config
        dest: /etc/ssh/sshd_config
        force: yes
      
    - name: restart sshd
      shell: systemctl restart sshd
