---
- hosts: all
  become: yes
  tasks: 
 
    - name: Ansible copy file force
      copy:
        src: ../files/.bash_aliases
        dest: ~/.bash_aliases 
        force: yes

    - name: update system 1
      command: apt-get update
      
    - name: update system 2
      command: apt-get upgrade -y
      
    - name: update system 3
      command: apt-get dist-upgrade -y
      
    - name: update system 4
      command: add-apt-repository universe
      
    - name: update system 5
      command: add-apt-repository multiverse
   
    - name: Install packages
      apt:
        name:
        - ccrypt
        - lsof
        - net-tools
        - htop
        - nano
        - wget
        - rsync
        - git
        - ncdu
        - nload
        - mc
        - iotop
        - mdadm
        - unzip
        - iperf3
        - mlocate
        - tree
        - p7zip
        - p7zip-full
        - p7zip-rar 
        - aptitude
        state: latest

    - name: Turn off Swap
      command: sudo swapoff -a 
      
    - name: Delete Swap if existing 
      command: sudo rm -rf /swapfile
      
    - name: create X GB swap file
      command: sudo fallocate -l {{ swap_size }}G /swapfile
      
    - name: chmod 600
      command: sudo chmod 600 /swapfile
      
    - name: format swap
      command: sudo mkswap /swapfile
      
    - name: enable swap
      command: sudo swapon /swapfile
      
    - name: add to fstab
      lineinfile:
        dest: /etc/fstab
        line: "/swapfile none swap sw 0 0"
        insertafter: EOF
        create: True

    - name: Configuring swappiness perm
      lineinfile:
        dest: /etc/sysctl.conf
        line: "vm.swappiness = 10"
        insertafter: EOF
        create: True
      
    - name: Configuring swappiness temp
      command: sysctl vm.swappiness=10
      
    - name: Configuring swappiness temp 2
      command: sudo sysctl -p

    - name: Change Timezone
      command: sudo timedatectl set-timezone {{ time_zone }}

    - name: Ansible copy file force
      copy:
        src: ../files/sshd_config
        dest: /etc/ssh/sshd_config
        force: yes
      
    - name: restart sshd
      shell: systemctl restart sshd
      
      
