---
- hosts: all
  become: yes
  tasks:
  - name: Ansible copy file force
    copy:
      src: ../files/.bash_aliases
      dest: ~/.bash_aliases 
      force: yes
    
  - name: source ~/.bashrc
    command: "source ~/.bash_aliases"
