- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Download Tomcat Redis Libraries
  get_url:
    url: "{{ tomcat_redis_lib_url }}"
    dest: "{{ tomcat_redis_lib_dest }}"
    headers: 'X-JFrog-Art-Api: {{ artifactory_api_key }}'

- name: Create Tomcat Group
  group:
    name: tomcat
    state: present

- name: Create a tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'
  register: tomcat_directory

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    mode: '0755'
    creates: /opt/tomcat/bin

- name: Extract Tomcat Redis Library
  unarchive:
    src: "{{ tomcat_redis_lib_dest }}"
    dest: /opt/tomcat/lib
    owner: tomcat
    group: tomcat
    mode: '0755'
    remote_src: yes

- name: Remove Tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/redis_lib.zip
    - /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz

- name: Copy tomcat service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Setting Execution permission to Tomcat Bin folder
  file:
    path: "/opt/tomcat/bin"
    mode: '0755'
    recurse: yes

- name: Create Tomcat Log Directory
  file:
    path: /opt/tomcat/logs
    state: directory
    mode: '0755'

- name: Create Tomcat Temp Folder
  file:
    path: /opt/tomcat/temp
    state: directory
    mode: '0755'

- name: Set UI access credentials and Redis Data Properties
  template:
    owner: tomcat
    group: tomcat
    src: tomcat-users.xml.j2
    dest: /opt/tomcat/conf/{{ item }}
    mode: '0644'
  loop:
    - tomcat-users.xml.j2
    - redis-data-cache.properties.j2
