- name: Download Vach configs
  get_url:
    url: "{{ vach_config_url }}"
    dest: "{{ vach_config_dest }}"
    headers: 'X-JFrog-Art-Api: {{ artifactory_api_key }}'

- name: Extract Vach configs
  unarchive:
    src: "{{ vach_config_dest }}"
    dest: "/home/{{ service_name }}/"
    owner: "{{ service_name }}"
    group: "{{ service_name }}"
    mode: '0755'
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Remove Tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vach_config_dest }}"
