---
- name: Converge
  hosts: remit
  become: yes
  vars_files:
    - ../../../../inventory/dev/group_vars/remit
    - ../../../../inventory/dev/group_vars/vault
  roles:
    - base
    - apache
