---
- hosts: all
  become: yes
  tasks:

  - name: Create database super user 
    mysql_user:
      login_user: root
      name: super
      password: "{{ mysql_password }}"
      priv: '*.*:ALL,GRANT'
      state: present
