---
- hosts: all
  become: yes
  tasks:

  - name: Create database super user 
    mysql_user:
      login_unix_socket : /var/run/mysqld/mysqld.sock
      name: super
      password: "{{ mysql_password }}"
      priv: '*.*:ALL,GRANT'
      update_password: always
      state: present
