---
- hosts: all
  become: yes
  tasks: 
  - name: Install packages
    apt:
      name:
      - mysql-server
      - apache2
      - php5-mysql
      state: latest
      cache_valid_time: 3600    # update cache if more than an hour old
